Book.create(title: "sky", pages: 150)
Book.create(title: "animal", pages: 1000)
Book.create(title: "babies", pages: 399)
Book.create(title: "food", pages: 24499)
Book.create(title: "family", pages: 400)
Book.create(title: "music", pages: 90)
